-- 코드를 입력하세요
SELECT MONTH(start_date) AS MONTH,
        CAR_ID AS CAR_ID,
        COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
AND car_id in (SELECT car_id
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
              GROUP BY car_id
              HAVING count(car_Id) >= 5)        
GROUP BY MONTH, CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC



