WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME WHERE HOUR < 23
)

SELECT A.HOUR, COUNT(HOUR(B.DATETIME)) 
 FROM TIME A LEFT JOIN ANIMAL_OUTS B
 ON A.HOUR = HOUR(B.DATETIME)
 GROUP BY A.HOUR


 
 