-- 코드를 입력하세요
SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW A INNER JOIN
(SELECT A.MEMBER_NAME, A.MEMBER_ID
FROM   MEMBER_PROFILE A INNER JOIN  REST_REVIEW B
     ON A.MEMBER_ID = B.MEMBER_ID
GROUP BY B.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1) B
ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY A.REVIEW_DATE, A.REVIEW_TEXT