-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS A INNER JOIN BOOK_SALES AS B ON A.book_id = B.book_id
WHERE DATE_FORMAT(sales_date, "%Y-%m") = "2022-01"
GROUP BY CATEGORY
ORDER BY A.CATEGORY
