-- 코드를 입력하세요
SELECT B.AUTHOR_ID, B.AUTHOR_NAME,A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES

FROM BOOK A INNER JOIN AUTHOR B 
     ON A.AUTHOR_ID = B.AUTHOR_ID 
     INNER JOIN BOOK_SALES C
     ON A.BOOK_ID = C.BOOK_ID

WHERE C.SALES_DATE BETWEEN "2022-01-01 00:00:00" AND "2022-01-31 23:59:59"
GROUP BY B.AUTHOR_NAME, A. CATEGORY
ORDER BY B.AUTHOR_ID, A.CATEGORY DESC
