-- 코드를 입력하세요
SELECT  TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(TO_CHAR(DATETIME, 'HH24')) AS COUNT
from animal_outs
WHERE  TO_CHAR(DATETIME, 'HH24') BETWEEN '09' AND '19'
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24')